// 1. 왜 맞았는가?
// -> INNER JOIN을 잘 사용했다.
// -> SUM(B.SALES)로 잘 묶어줬다.
// -> INNER JOIN을 할 때, ON으로 잘 묶어줬다.
// -> SALES_DATE를 BETWEEN으로 잘 잡아줬다. 
// -> GROUP BY랑 ORDER BY로 잘해줬다. 

SELECT A.CATEGORY, SUM(B.SALES) AS TOTAL_SALES FROM BOOK AS A INNER JOIN BOOK_SALES AS B ON A.BOOK_ID = B.BOOK_ID WHERE SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31' GROUP BY CATEGORY ORDER BY CATEGORY;
